name: Deploy to AWS

on:
  workflow_run:
    workflows: ['Publish to Docker Hub']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package
        run: zip -r deploy.zip * -x "**node_modules**" -x "**res**"

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Format timestamp
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: '${{ steps.current-time.outputs.time }}'
          replace-with: '-'
          flags: 'g'

      - name: Deploy to AWS
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: cy17-react-app-starter
          environment_name: Cy17reactappstarter-ecs
          version_label: 'cy17-react-app-starter-${{ steps.format-time.outputs.replaced }}'
          region: us-east-1
          deployment_package: deploy.zip
